title: ADVEC
subtitle: "ADVEC @ 2017"
description: "ADVEC @ 2017."
author: LIUG
timezone: UTC
url: https://advec.org
root: /
permalink: :title/
code_dir: downloads/code
new_post_name: :title.jade # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: advec
deploy:
  type:
  repo:

facebook: advecoficiala
instagram: advecoficial
twitter: advecoficial
youtube: advitoriaemcristo
